// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, slug, city, country, tier, status, logo_url, description, schedule)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, slug, city, country, tier, status, logo_url, description, schedule, created_at, updated_at
`

type CreateOrganizationParams struct {
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	City        pgtype.Text `json:"city"`
	Country     string      `json:"country"`
	Tier        string      `json:"tier"`
	Status      string      `json:"status"`
	LogoUrl     pgtype.Text `json:"logo_url"`
	Description pgtype.Text `json:"description"`
	Schedule    []byte      `json:"schedule"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.Name,
		arg.Slug,
		arg.City,
		arg.Country,
		arg.Tier,
		arg.Status,
		arg.LogoUrl,
		arg.Description,
		arg.Schedule,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.City,
		&i.Country,
		&i.Tier,
		&i.Status,
		&i.LogoUrl,
		&i.Description,
		&i.Schedule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, name, slug, city, country, tier, status, logo_url, description, schedule, created_at, updated_at FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganization(ctx context.Context, id pgtype.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.City,
		&i.Country,
		&i.Tier,
		&i.Status,
		&i.LogoUrl,
		&i.Description,
		&i.Schedule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, slug, city, country, tier, status, logo_url, description, schedule, created_at, updated_at FROM organizations WHERE slug = $1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.City,
		&i.Country,
		&i.Tier,
		&i.Status,
		&i.LogoUrl,
		&i.Description,
		&i.Schedule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, name, slug, city, country, tier, status, logo_url, description, schedule, created_at, updated_at FROM organizations ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListOrganizationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.City,
			&i.Country,
			&i.Tier,
			&i.Status,
			&i.LogoUrl,
			&i.Description,
			&i.Schedule,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
