// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, phone, email, name, role, organization_id, status, language, created_at FROM users WHERE email = $1 AND organization_id = $2
`

type GetUserByEmailParams struct {
	Email          pgtype.Text `json:"email"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.Email, arg.OrganizationID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.OrganizationID,
		&i.Status,
		&i.Language,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmailAdmin = `-- name: GetUserByEmailAdmin :one
SELECT id, phone, email, name, role, organization_id, status, language, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmailAdmin(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailAdmin, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.OrganizationID,
		&i.Status,
		&i.Language,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, phone, email, name, role, organization_id, status, language, created_at FROM users WHERE id = $1 AND organization_id = $2
`

type GetUserByIDParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, arg.ID, arg.OrganizationID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.OrganizationID,
		&i.Status,
		&i.Language,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByIDAdmin = `-- name: GetUserByIDAdmin :one
SELECT id, phone, email, name, role, organization_id, status, language, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByIDAdmin(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIDAdmin, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.OrganizationID,
		&i.Status,
		&i.Language,
		&i.CreatedAt,
	)
	return i, err
}
