/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppStudentsRouteImport } from './routes/_app/students'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppAttendanceRouteImport } from './routes/_app/attendance'
import { Route as AppSessionIndexRouteImport } from './routes/_app/session/index'
import { Route as AppPlatformIndexRouteImport } from './routes/_app/platform/index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppSessionCompleteRouteImport } from './routes/_app/session/complete'
import { Route as AppSessionStudentIdRouteImport } from './routes/_app/session/$studentId'
import { Route as AppPlatformOrganizationsRouteImport } from './routes/_app/platform/organizations'
import { Route as AppAdminRegistrationsRouteImport } from './routes/_app/admin/registrations'
import { Route as AppAdminLandingRouteImport } from './routes/_app/admin/landing'
import { Route as AppAdminHalaqatRouteImport } from './routes/_app/admin/halaqat'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionIndexRoute = AppSessionIndexRouteImport.update({
  id: '/session/',
  path: '/session/',
  getParentRoute: () => AppRoute,
} as any)
const AppPlatformIndexRoute = AppPlatformIndexRouteImport.update({
  id: '/platform/',
  path: '/platform/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionCompleteRoute = AppSessionCompleteRouteImport.update({
  id: '/session/complete',
  path: '/session/complete',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionStudentIdRoute = AppSessionStudentIdRouteImport.update({
  id: '/session/$studentId',
  path: '/session/$studentId',
  getParentRoute: () => AppRoute,
} as any)
const AppPlatformOrganizationsRoute =
  AppPlatformOrganizationsRouteImport.update({
    id: '/platform/organizations',
    path: '/platform/organizations',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminRegistrationsRoute = AppAdminRegistrationsRouteImport.update({
  id: '/admin/registrations',
  path: '/admin/registrations',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminLandingRoute = AppAdminLandingRouteImport.update({
  id: '/admin/landing',
  path: '/admin/landing',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminHalaqatRoute = AppAdminHalaqatRouteImport.update({
  id: '/admin/halaqat',
  path: '/admin/halaqat',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/attendance': typeof AppAttendanceRoute
  '/settings': typeof AppSettingsRoute
  '/students': typeof AppStudentsRoute
  '/login': typeof AuthLoginRoute
  '/admin/halaqat': typeof AppAdminHalaqatRoute
  '/admin/landing': typeof AppAdminLandingRoute
  '/admin/registrations': typeof AppAdminRegistrationsRoute
  '/platform/organizations': typeof AppPlatformOrganizationsRoute
  '/session/$studentId': typeof AppSessionStudentIdRoute
  '/session/complete': typeof AppSessionCompleteRoute
  '/admin/': typeof AppAdminIndexRoute
  '/platform/': typeof AppPlatformIndexRoute
  '/session/': typeof AppSessionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/attendance': typeof AppAttendanceRoute
  '/settings': typeof AppSettingsRoute
  '/students': typeof AppStudentsRoute
  '/login': typeof AuthLoginRoute
  '/admin/halaqat': typeof AppAdminHalaqatRoute
  '/admin/landing': typeof AppAdminLandingRoute
  '/admin/registrations': typeof AppAdminRegistrationsRoute
  '/platform/organizations': typeof AppPlatformOrganizationsRoute
  '/session/$studentId': typeof AppSessionStudentIdRoute
  '/session/complete': typeof AppSessionCompleteRoute
  '/admin': typeof AppAdminIndexRoute
  '/platform': typeof AppPlatformIndexRoute
  '/session': typeof AppSessionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/students': typeof AppStudentsRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/halaqat': typeof AppAdminHalaqatRoute
  '/_app/admin/landing': typeof AppAdminLandingRoute
  '/_app/admin/registrations': typeof AppAdminRegistrationsRoute
  '/_app/platform/organizations': typeof AppPlatformOrganizationsRoute
  '/_app/session/$studentId': typeof AppSessionStudentIdRoute
  '/_app/session/complete': typeof AppSessionCompleteRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/platform/': typeof AppPlatformIndexRoute
  '/_app/session/': typeof AppSessionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/settings'
    | '/students'
    | '/login'
    | '/admin/halaqat'
    | '/admin/landing'
    | '/admin/registrations'
    | '/platform/organizations'
    | '/session/$studentId'
    | '/session/complete'
    | '/admin/'
    | '/platform/'
    | '/session/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/settings'
    | '/students'
    | '/login'
    | '/admin/halaqat'
    | '/admin/landing'
    | '/admin/registrations'
    | '/platform/organizations'
    | '/session/$studentId'
    | '/session/complete'
    | '/admin'
    | '/platform'
    | '/session'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/attendance'
    | '/_app/settings'
    | '/_app/students'
    | '/_auth/login'
    | '/_app/'
    | '/_app/admin/halaqat'
    | '/_app/admin/landing'
    | '/_app/admin/registrations'
    | '/_app/platform/organizations'
    | '/_app/session/$studentId'
    | '/_app/session/complete'
    | '/_app/admin/'
    | '/_app/platform/'
    | '/_app/session/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/students': {
      id: '/_app/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/session/': {
      id: '/_app/session/'
      path: '/session'
      fullPath: '/session/'
      preLoaderRoute: typeof AppSessionIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/platform/': {
      id: '/_app/platform/'
      path: '/platform'
      fullPath: '/platform/'
      preLoaderRoute: typeof AppPlatformIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/session/complete': {
      id: '/_app/session/complete'
      path: '/session/complete'
      fullPath: '/session/complete'
      preLoaderRoute: typeof AppSessionCompleteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/session/$studentId': {
      id: '/_app/session/$studentId'
      path: '/session/$studentId'
      fullPath: '/session/$studentId'
      preLoaderRoute: typeof AppSessionStudentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/platform/organizations': {
      id: '/_app/platform/organizations'
      path: '/platform/organizations'
      fullPath: '/platform/organizations'
      preLoaderRoute: typeof AppPlatformOrganizationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/registrations': {
      id: '/_app/admin/registrations'
      path: '/admin/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AppAdminRegistrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/landing': {
      id: '/_app/admin/landing'
      path: '/admin/landing'
      fullPath: '/admin/landing'
      preLoaderRoute: typeof AppAdminLandingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/halaqat': {
      id: '/_app/admin/halaqat'
      path: '/admin/halaqat'
      fullPath: '/admin/halaqat'
      preLoaderRoute: typeof AppAdminHalaqatRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudentsRoute: typeof AppStudentsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminHalaqatRoute: typeof AppAdminHalaqatRoute
  AppAdminLandingRoute: typeof AppAdminLandingRoute
  AppAdminRegistrationsRoute: typeof AppAdminRegistrationsRoute
  AppPlatformOrganizationsRoute: typeof AppPlatformOrganizationsRoute
  AppSessionStudentIdRoute: typeof AppSessionStudentIdRoute
  AppSessionCompleteRoute: typeof AppSessionCompleteRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppPlatformIndexRoute: typeof AppPlatformIndexRoute
  AppSessionIndexRoute: typeof AppSessionIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAttendanceRoute: AppAttendanceRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudentsRoute: AppStudentsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminHalaqatRoute: AppAdminHalaqatRoute,
  AppAdminLandingRoute: AppAdminLandingRoute,
  AppAdminRegistrationsRoute: AppAdminRegistrationsRoute,
  AppPlatformOrganizationsRoute: AppPlatformOrganizationsRoute,
  AppSessionStudentIdRoute: AppSessionStudentIdRoute,
  AppSessionCompleteRoute: AppSessionCompleteRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppPlatformIndexRoute: AppPlatformIndexRoute,
  AppSessionIndexRoute: AppSessionIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
